---
title: "POMA: Statistical analysis tool for omics data"
subtitle: "Exploratory Data Analysis - Expanded Heatmap"
date: '`r format(Sys.Date(), "%B, %Y")`'
output: 
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
params:
  corrected: NA
---

```{r, echo = FALSE, warning = FALSE, comment = NA, message=FALSE}
# This file is part of POMA.

# POMA is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# POMA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with POMA. If not, see <https://www.gnu.org/licenses/>.

corrected <- params$corrected
```

```{r, echo = FALSE, warning = FALSE, comment = NA, message=FALSE}
###  EXPANDED HEAT MAP ON THE NORMALIZED MATRIX

exp.heatmap <- function(e,fnm,h,tit)
{
  cls <- brewer.pal(8,"Dark2")[as.integer(as.factor(pData(e)[,fnm]))]
  ###  Filter dataset 
  data <- exprs(e)
  data <- data[filter.flags(exprs(e)),]
  ###  Expression to write data on the heatmap
  add.expr <- expression(
  { par(mar = c(margins[1], 0, 0, margins[2]))
    for(j in 1:ncol(SpC.expr))
     text(j,1:nrow(SpC.expr),labels=round(SpC.expr[rowInd,colInd[j]],1),
          cex=0.6,font=2,col=tracecol)
  })
  gtit <- paste("Heat map - ",tit,sep="")
  hm <- heatmap.2jg(t(scale(t(data))),col=greenred(255),trace="none",
            key=FALSE,cexRow=0.6,cexCol=0.7,margins=c(5,6),dendrogram="both",
            add.expr=add.expr,lhei=c(2,h-3),SpC.expr=data,
            ColSideColors=cls)
}
```

```{r, echo = FALSE, warning = FALSE, comment = NA, message=FALSE}
h <- nrow(exprs(corrected))/(2.54/0.35)
pdf(file = paste(Sys.Date(), "_expanded_heatmap.pdf",sep=""), width=7, height=h)

exp.heatmap(corrected, "Treatment", h = h, tit = "")
dev.off()
insert(output,paste("  See: ",pdf.flnm,"_expanded_heatmap.pdf", sep=""))
```

