
library(shiny)
library(DT)
library(shinydashboard)
library(tidyverse)
library(RColorBrewer)
library(dendextend)
library(mixOmics)
library(msmsEDA)
library(dashboardthemes)
library(shinyBS)
library(Biobase)
library(MSnbase)
library(reshape2)
library(gplots)
# library(plotly)